### ISSUE TITLE
Cyclic dependency error is cached hard

### ISSUE THREAD

**Issue by michaellopez** [algesten/fnug#17]
When a cycling dependency error is found the results seem to be cached pretty hard.
Even if you fix the bad dependency the previous error is still returned. Having checkModified set to something other than 0 does not impact the results. Restarting jetty fixes it.

**Comment by algesten** [comment]
Fixed problem with doing checkModified() when ResourceCollection is being built. This closed by 4df853f994f15fa74febad744410fcdaa4cd0972
